version: '3.8'

services:
  ambev.developerevaluation.frontend:
    container_name: ambev_developer_evaluation_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src
    networks:
      - ambev-evaluation-network

networks:
  ambev-evaluation-network:
    external: true 